version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Branch name
          command: echo "${CIRCLE_BRANCH}"
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 bucket
          command: aws s3 sync . s3://codersuk-craftyjs-game/${CIRCLE_BRANCH} --exclude '.circleci/*' --exclude '.git/*'  
